test: fix build with clang 21
[ upstream commit bec307d512373403a28d447d0d54b191471bc624 ]

Fix the following errors seen with clang 21.1.4

app/test/test_event_dma_adapter.c:532:32: error: variable 'event' is
uninitialized when passed as a const pointer argument here
[-Werror,-Wuninitialized-const-pointer]

app/test/test_trace.c:201:29: error: variable 'tmp' is uninitialized
when passed as a const pointer argument here
[-Werror,-Wuninitialized-const-pointer]

Fixes: 4925e15a1614 ("trace: add trace point emit for blob")
Fixes: a276e7c8fbb3 ("test/event: add DMA adapter auto-test")

Signed-off-by: Jerin Jacob <jerinj@marvell.com>
Acked-by: Amit Prakash Shukla <amitprakashs@marvell.com>
Signed-off-by: David Marchand <david.marchand@redhat.com>