examples/ethtool: fix size of mempool name
[ upstream commit b3a5c3281d8accc2d8dc4c0e878302a7b791792c ]

Use RTE_MEMPOOL_NAMESIZE for str_name buffer size instead of the
hardcoded value 16, which was insufficient as the format
string "pkt_pool%i" can produce up to 19 bytes (8 for "pkt_pool",
up to 10 for integer value, and 1 for null terminator).

This issue can be seen when compiling in debug mode (--buildtype=debug):

examples/ethtool/ethtool-app/main.c: In function 'setup_ports':
main.c:115:49: error: '%i' directive output may be truncated
writing between 1 and 10 bytes into a region of size 8
  115 |                 snprintf(str_name, 16, "pkt_pool%i", idx_port);
	  |                                                 ^~
Fixes: bda68ab9d1e7 ("examples/ethtool: add user-space ethtool sample application")

Signed-off-by: Shani Peretz <shperetz@nvidia.com>
Acked-by: Stephen Hemminger <stephen@networkplumber.org>